#!/usr/bin/env bash

# LICENSE: CC0

# Dependencies:
# fzf, jq, youtube-dl as well as bash, cut and cat :P
# Optionally: mpv to play the videos

N=50
CONSUMER="mpv"

while [[ $# -gt 0 ]]
do
    case "$1" in
        -h|--help)
            echo 'USAGE yt [OPTIONS] "SEARCH STRING"'
            echo ''
            echo 'Search and play YouTube videos.'
            echo ''
            echo '  -h, --help         Show this help.'
            echo '  -n, --num-results  Number of search results to fetch, defaults to 50.'
            echo '  -c, --consumer     Command to be called with URLs of selected videos,'
            echo '                     default is mpv.'
            echo '  -v, --version      Print version.'
            echo '  --                 Stops interpreting the following arguments as options.'
            exit
            ;;
        -n|--num-results)
            N="$2"
            if ! [[ "$N" =~ ^[0-9]+$ ]]
            then
                echo "'$N' is not an integer!"
                exit 1
            fi
            shift 2
            ;;
        -c|--consumer)
            CONSUMER="$2"
            if [ ! "$CONSUMER" ]
            then
                echo "Consumer command is missing!"
                exit 1
            fi
            shift 2
            ;;
        -v|--version)
            echo "1.0"
            exit
            ;;
        --)
            shift
            break
            ;;
        *)
            break
            ;;
    esac
done

SEARCH="$*"

if [ ! "$SEARCH" ]
then
	SEARCH=$(printf "" | eval dmenu -p Search:)
fi

JSON="$(youtube-dl ytsearch$N:"$SEARCH" -j --flat-playlist)"
TITLE=$(echo $JSON | jq -r ".title" | dmenu -i -l 30)
URLS=$(echo $JSON | jq -r "select(.title == \"$TITLE\") | .url")

if [ ! "$URLS" ]; then
    echo "No video(s) selected!"
    exit 1
fi

$CONSUMER https://www.youtube.com/watch?v=$URLS
